obj-$(CONFIG_PANEL_GENERIC_DPI) += panel-generic-dpi.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-nl8048hl11-01b.o
obj-$(CONFIG_PANEL_S6E8AA0) += panel-s6e8aa0.o
obj-$(CONFIG_PANEL_S6E8AA0A01) += panel-s6e8aa0a01.o  smart_dimming.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_TC358765) += panel-tc358765.o
obj-$(CONFIG_PANEL_LD9040) += panel-ld9040.o
obj-$(CONFIG_PANEL_LTN070NL01) += panel-ltn070nl01.o
obj-$(CONFIG_PANEL_LTN101AL03) += panel-ltn101al03.o
obj-$(CONFIG_PANEL_HV070WX1) += panel-hv070wx1.o
obj-$(CONFIG_PANEL_NT71391) += panel-nt71391.o
obj-$(CONFIG_IMGSENSOR_CMC624) += cmc624.o
obj-$(CONFIG_PANEL_LMS501KF07) += panel-lms501kf07.o