SDCARDFSJB_VERSION="0.1"

EXTRA_CFLAGS += -DSDCARDFSJB_VERSION=\"$(SDCARDFSJB_VERSION)\"

obj-$(CONFIG_SDCARD_FS_JB) += sdcardfsjb.o

sdcardfsjb-y := dentry.o file.o inode.o main.o super.o lookup.o mmap.o
