/* arch/arm/mach-omap2/board-gokey-muxset-r00.c
 *
 * Copyright (C) 2011 Samsung Electronics Co, Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <linux/gpio.h>

#include "board-gokey.h"

#include "mux.h"
#include "mux44xx.h"
#include "omap_muxtbl.h"
#include "omap44xx_muxtbl.h"
#include "sec_muxtbl.h"

static struct omap_muxtbl muxtbl[] __initdata = {
	/* [-----] gpmc_ad0 -  - NAND_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD0, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(0)"),
	/* [-----] gpmc_ad1 -  - NAND_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD1, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(1)"),
	/* [-----] gpmc_ad2 -  - NAND_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD2, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(2)"),
	/* [-----] gpmc_ad3 -  - NAND_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD3, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(3)"),
	/* [-----] gpmc_ad4 -  - NAND_D(4) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD4, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(4)"),
	/* [-----] gpmc_ad5 -  - NAND_D(5) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD5, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(5)"),
	/* [-----] gpmc_ad6 -  - NAND_D(6) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD6, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(6)"),
	/* [-----] gpmc_ad7 -  - NAND_D(7) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD7, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_D(7)"),
	/* [--OUT] gpmc_ad8 - gpio_32 - MUTE_ON */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD8,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     32, "MUTE_ON"),
	/* [-N-C-] gpmc_ad9 - gpio_33 -NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD9, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     33, "gpmc_ad9.nc"),
	/* [--OUT] gpmc_ad10 - gpio_34 - eMMC_LDO */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD10, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     34, "eMMC_LDO"),
	/* [IN---] gpmc_ad11 - gpio_35 - LCD_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD11,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     35, "LCD_nRST"),
	/* [-N-C-] gpmc_ad12 - gpio_36 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD12, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     36, "gpmc_ad12.nc"),
	/* [--OUT] gpmc_ad13 - gpio_37 - UART_SEL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD13, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     37, "UART_SEL"),
	/* [-N-C-] gpmc_ad14 - gpio_38 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD14, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     38, "gpmc_ad14.nc"),
	/* [IN---] gpmc_ad15 - gpio_39 - TA_CURRENT_SEL_AP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD15, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     39, "TA_CURRENT_SEL_AP"),
	/* [IN---] gpmc_a16 - gpio_40 - CODEC_LDO_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A16, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     40, "CODEC_LDO_EN"),
	/* [-N-C-] gpmc_a17 - gpio_41 - 3M_nSTBY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A17, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     41, "3M_nSTBY"),
	/* [--OUT] gpmc_a18 - gpio_42 - CAM_HWEN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A18, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT |
		     OMAP_PIN_OFF_OUTPUT_LOW,
		     42, "CAM_HWEN"),
	/* [--OUT] gpmc_a19 - gpio_43 - CAM_PG */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A19, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     43, "CAM_PG"),
	/* [IN---] gpmc_a20 - gpio_44 - FUEL_ALERT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A20,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     44, "FUEL_ALERT"),
	/* [IN---] gpmc_a21 - gpio_45 - ACCEL_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A21, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     45, "ACCEL_INT"),
	/* [IN---] gpmc_a22 - gpio_46 - TSP_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A22, OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     46, "TSP_INT"),
	/* [--OUT] gpmc_a23 - gpio_47 - CAM_INTB */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A23, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     47, "CAM_INTB"),
	/* [-N-C-] gpmc_a24 - gpio_48 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A24, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     48, "gpmc_a24.nc"),
	/* [IN---] gpmc_a25 - gpio_49 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A25, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     49, "gpmc_a25.nc"),
	/* [--OUT] gpmc_ncs0 - gpio_50 - 3M_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS0,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     50, "3M_nRST"),
	/* [--OUT] gpmc_ncs1 - gpio_51 - VT_CAM_nSTBY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS1,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     51, "VT_CAM_nSTBY"),
	/* [IN---] gpmc_ncs2 - gpio_52 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     52, "gpmc_ncs2.nc"),
	/* [--OUT] gpmc_ncs3 - gpio_53 - SENSOR_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS3, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     53, "SENSOR_EN"),
	/* [--OUT] gpmc_nwp - gpio_54 - TOUCH_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NWP, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     54, "TOUCH_EN"),
	/* [IN---] gpmc_clk - gpio_55 - JIG_ON_18 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_CLK, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     55, "JIG_ON_18"),
	/* [IN---] gpmc_nadv_ale - gpio_56 - CP_DUMP_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NADV_ALE, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     56, "CP_DUMP_INT"),
	/* [-----] gpmc_noe -  - NAND_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NOE, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_CLK"),
	/* [-----] gpmc_nwe -  - NAND_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NWE, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "NAND_CMD"),
	/* [-N-C-] gpmc_nbe0_cle - gpio_59 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NBE0_CLE, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     59, "gpmc_nbe0_cle.nc"),
	/* [--OUT] gpmc_nbe1 - gpio_60 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NBE1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     60, "gpmc_nbe1.nc"),
	/* [IN---] gpmc_wait0 - gpio_61 - FUEL_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT0, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     61, "FUEL_SCL_1.8V"),
	/* [IN---] gpmc_wait1 - gpio_62 - FUEL_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT1, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     62, "FUEL_SDA_1.8V"),
	/* [-----] gpmc_wait2 - gpio_100 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     100, "gpmc_wait2.nc"),
	/* [--OUT] gpmc_ncs4 - gpio_101 - BL_CTRL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS4,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     101, "BL_CTRL"),
	/* [-N-C-] gpmc_ncs5 - gpio_102 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     102, "gpmc_ncs5.nc"),
	/* [--OUT] gpmc_ncs6 - gpio_103 - BT_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS6, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     103, "BT_EN"),
	/* [--OUT] gpmc_ncs7 - gpio_104 - WLAN_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS7, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     104, "WLAN_EN"),
	/* [-N-C-] hdmi_hpd - gpio_63 - HDMI_HPD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_HPD, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     63, "HDMI_HPD"),
	/* [-----] hdmi_cec - gpio_64 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_CEC, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     64, "hdmi_cec.nc"),
	/* [IN---] hdmi_ddc_scl - gpio_65 - NC" */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_DDC_SCL, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     65, "hdmi_ddc_scl.nc"),
	/* [IN---] hdmi_ddc_sda - gpio_66 - NC" */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_DDC_SDA, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     66, "hdmi_ddc_sda.nc"),
	/* [-----] csi21_dx0 - gpi_67 - 3M_CLK_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     67, "3M_CLK_P"),
	/* [-----] csi21_dy0 - gpi_68 - 3M_CLK_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     68, "3M_CLK_N"),
	/* [-----] csi21_dx1 - gpi_69 - 3M_DP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     69, "3M_DP"),
	/* [-----] csi21_dy1 - gpi_70 - 3M_DN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     70, "3M_DN"),
	/* [-N-C-] csi21_dx2 - gpi_71 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     71, "csi21_dx2.nc"),
	/* [-N-C-] csi21_dy2 - gpi_72 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     72, "csi21_dy2.nc"),
	/* [IN---] csi21_dx3 - gpi_73 - HW_REV3 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX3, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     73, "HW_REV3"),
	/* [IN---] csi21_dy3 - gpi_74 - HW_REV2 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY3, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     74, "HW_REV2"),
	/* [IN---] csi21_dx4 - gpi_75 - HW_REV1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX4, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     75, "HW_REV1"),
	/* [IN---] csi21_dy4 - gpi_76 - HW_REV0 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY4, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     76, "HW_REV0"),
	/* [-----] csi22_dx0 - gpi_77 - VT_CAM_CLK_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DX0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     77, "VT_CAM_CLK_P"),
	/* [-----] csi22_dy0 - gpi_78 - VT_CAM_CLK_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DY0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     78, "VT_CAM_CLK_N"),
	/* [-----] csi22_dx1 - gpi_79 - VT_CAM_DP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DX1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     79, "VT_CAM_DP"),
	/* [-----] csi22_dy1 - gpi_80 - VT_CAM_DN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DY1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     80, "VT_CAM_DN"),
	/* [-N-C-] cam_shutter - gpio_81 - WLAN_HOST_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_SHUTTER,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     81, "WLAN_HOST_WAKE"),
	/* [--OUT] cam_strobe - gpio_82 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_STROBE, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     82, "cam_strobe.nc"),
	/* [IN---] cam_globalreset - gpio_83 - BT_HOST_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_GLOBALRESET,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     83, "BT_HOST_WAKE"),
	/* [-N-C-] usbb1_ulpitll_clk - gpio_84 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_CLK,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     84, "usbb1_ulpitll_clk.nc"),
	/* [-N-C-] usbb1_ulpitll_stp - gpio_85 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_STP,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     85, "usbb1_ulpitll_stp.nc"),
	/* [-N-C-] usbb1_ulpitll_dir - gpio_86 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DIR,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     86, "usbb1_ulpitll_dir.nc"),
	/* [-N-C-] usbb1_ulpitll_nxt - gpio_87 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_NXT,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     87, "usbb1_ulpitll_nxt.nc"),
	/* [-----] usbb1_ulpitll_dat0 - gpio_88 - SD_LDO */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT0,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     88, "SD_LDO"),
	/* [-N-C-] usbb1_ulpitll_dat1 - gpio_89 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT1,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     89, "usbb1_ulpitll_dat1.nc"),
	/* [-N-C-] usbb1_ulpitll_dat2 - gpio_90 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT2,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     90, "usbb1_ulpitll_dat2.nc"),
	/* [-N-C-] usbb1_ulpitll_dat3 - gpio_91 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT3,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     91, "usbb1_ulpitll_dat3.nc"),
	/* [IN---] usbb1_ulpitll_dat4 - gpio_92 - BOOT_MODE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT4, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     92, "BOOT_MODE"),
	/* [--OUT] usbb1_ulpitll_dat5 - gpio_93 - BT_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT5, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     93, "BT_WAKE"),
#if defined(CONFIG_PANEL_NT35516)
	/* [-----] usbb1_ulpitll_dat6 - gpio_94 - LED_BACKLIGHT_PWM */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT6,
		     OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     94, "LED_BACKLIGHT_PWM"),
#elif defined(CONFIG_PANEL_LMS579NF01)
	/* [-----] usbb1_ulpitll_dat6 - gpio_94 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT6,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     94, "usbb1_ulpitll_dat6.nc"),
#elif defined(CONFIG_PANEL_LMS501KF07)
	/* [-----] usbb1_ulpitll_dat6 - gpio_94 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT6,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     94, "usbb1_ulpitll_dat6.nc"),
#endif
	/* [--OUT] usbb1_ulpitll_dat7 - gpio_95 - MOTOR_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT7, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     95, "MOTOR_EN"),
	/* [-N-C-] usbb1_hsic_data - gpio_96 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_HSIC_DATA, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     96, "usbb1_hsic_data.nc"),
	/* [-N-C-] usbb1_hsic_strobe - gpio_97 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_HSIC_STROBE,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     97, "usbb1_hsic_strobe.nc"),
	/* [IN---] sim_io - gpio_wk0 - DET_3.5 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SIM_IO,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     0, "sim_io.nc"),
	/* [IN---] sim_clk - gpio_wk1 - 5V_DET */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SIM_CLK,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     1, "5V_DET"),
	/* [-N-C-] sim_reset - gpio_wk2 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SIM_RESET,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     2, "sim_reset.nc"),
	/* [IN---] sim_cd - gpio_wk3 - EXT_WAKEUP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SIM_CD,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     3, "EXT_WAKEUP"),
	/* [IN---] sim_pwrctrl - gpio_wk4 - EAR_SEND_END */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SIM_PWRCTRL,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     4, "EAR_SEND_END"),
	/* [IN---] usbc1_icusb_dp - gpio_98 - nc */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBC1_ICUSB_DP, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     98, "usbc1_icisb_dp.nc"),
	/* [IN---] usbc1_icusb_dm - gpio_99 -nc */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBC1_ICUSB_DM, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     99, "usbc1_icusb_dm.nc"),
	/* [-----] sdmmc1_clk - gpio_100 - T_FLASH_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_CLK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     100, "T_FLASH_CLK"),
	/* [-----] sdmmc1_cmd - gpio_101 - T_FLASH_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_CMD, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     101, "T_FLASH_CMD"),
	/* [-----] sdmmc1_dat0 - gpio_102 - T_FLASH_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT0, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     102, "T_FLASH_D(0)"),
	/* [-----] sdmmc1_dat1 - gpio_103 - T_FLASH_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT1, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     103, "T_FLASH_D(1)"),
	/* [-----] sdmmc1_dat2 - gpio_104 - T_FLASH_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT2, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     104, "T_FLASH_D(2)"),
	/* [-----] sdmmc1_dat3 - gpio_105 - T_FLASH_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT3, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     105, "T_FLASH_D(3)"),
	/* [-N-C-] sdmmc1_dat4 - gpio_106 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     106, "sdmmc1_dat4.nc"),
	/* [-N-C-] sdmmc1_dat5 - gpio_107 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     107, "sdmmc1_dat5.nc"),
	/* [-N-C-] sdmmc1_dat6 - gpio_108 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT6, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     108, "sdmmc1_dat6.nc"),
	/* [-N-C-] sdmmc1_dat7 - gpio_109 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT7, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     109, "sdmmc1_dat7.nc"),
	/* [-N-C-] abe_mcbsp2_clkx - gpio_110 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_CLKX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     110, "abe_mcbsp2_clkx.nc"),
	/* [-N-C-] abe_mcbsp2_dr - gpio_111 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_DR, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     111, "abe_mcbsp2_dr.nc"),
	/* [-N-C-] abe_mcbsp2_dx - gpio_112 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_DX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     112, "abe_mcbsp2_dx.nc"),
	/* [-N-C-] abe_mcbsp2_fsx - gpio_113 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_FSX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     113, "abe_mcbsp2_fsx.nc"),
	/* [-N-C-] abe_mcbsp1_clkx - gpio_114 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_CLKX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     114, "abe_mcbsp1_clkx.nc"),
	/* [-N-C-] abe_mcbsp1_dr - gpio_115 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_DR, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     115, "abe_mcbsp1_dr.nc"),
	/* [-N-C-] abe_mcbsp1_dx - gpio_116 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_DX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     116, "abe_mcbsp1_dx.nc"),
	/* [-N-C-] abe_mcbsp1_fsx - gpio_117 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_FSX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     117, "abe_mcbsp1_fsx.nc"),
	/* [-----] abe_pdm_ul_data -  - AP_I2S_DIN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_UL_DATA, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_DIN"),
	/* [-----] abe_pdm_dl_data -  - AP_I2S_DOUT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_DL_DATA, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_DOUT"),
	/* [-----] abe_pdm_frame -  - AP_I2S_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_FRAME, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_CLK"),
	/* [-----] abe_pdm_lb_clk -  - AP_I2S_SYNC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_LB_CLK, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_SYNC"),
	/* [-N-C-] abe_clks - gpio_118 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_CLKS, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     118, "abe_clks.nc"),
	/* [-N-C-] abe_dmic_clk1 - gpio_119 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_CLK1,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     119, "abe_dmic_clk1.nc"),
	/* [-N-C-] abe_dmic_din1 - gpio_120 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     120, "abe_dmic_din1.nc"),
	/* [IN---] abe_dmic_din2 - gpio_121 - JACK_nINT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN2, OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     121, "JACK_nINT"),
	/* [-N-C-] abe_dmic_din3 - gpio_122 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     122, "abe_dmic_din3.nc"),
	/* [-----] uart2_cts - gpio_123 - BT_UART_CTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_CTS, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     123, "BT_UART_CTS"),
	/* [-----] uart2_rts - gpio_124 - BT_UART_RTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_RTS, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     124, "BT_UART_RTS"),
	/* [-----] uart2_rx - gpio_125 - BT_UART_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_RX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     125, "BT_UART_RXD"),
	/* [-----] uart2_tx - gpio_126 - BT_UART_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_TX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     126, "BT_UART_TXD"),
	/* [-N-C-] hdq_sio - gpio_127 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDQ_SIO, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     127, "hdq_sio.nc"),
	/* [-----] i2c1_scl -  - PHEONIX_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C1_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PHEONIX_I2C_SCL"),
	/* [-----] i2c1_sda -  - PHEONIX_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C1_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PHEONIX_I2C_SDA"),
	/* [-----] i2c2_scl - gpio_128 - CAM_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C2_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     128, "CAM_I2C_SCL"),
	/* [-----] i2c2_sda - gpio_129 - CAM_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C2_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     129, "CAM_I2C_SDA"),
	/* [-----] i2c3_scl - gpio_130 - TSP_I2C_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C3_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     130, "TSP_I2C_SCL_1.8V"),
	/* [-----] i2c3_sda - gpio_131 - TSP_I2C_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C3_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     131, "TSP_I2C_SDA_1.8V"),
	/* [-----] i2c4_scl - gpio_132 - SENSOR_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C4_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     132, "GEN_I2C_SCL"),
	/* [-----] i2c4_sda - gpio_133 - SENSOR_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C4_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     133, "GEN_I2C_SDA"),
	/* [-----] sr_scl -  - PMIC_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SR_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PMIC_I2C_SCL"),
	/* [-----] sr_sda -  - PMIC_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SR_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PMIC_I2C_SDA"),
	/* [-N-C-] mcspi1_clk - gpio_134 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CLK, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     134, "mcspi1_clk.nc"),
	/* [-N-C-] mcspi1_somi - gpio_135 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_SOMI, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     135, "mcspi1_somi.nc"),
	/* [-N-C-] mcspi1_simo - gpio_136 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_SIMO, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     136, "mcspi1_simo.nc"),
	/* [-N-C-] mcspi1_cs0 - gpio_137 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     137, "mcspi1_cs0.nc"),
	/* [-----] mcspi1_cs1 - gpio_138 - GPS_UART_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS1, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     138, "GPS_UART_RXD"),
	/* [IN---] mcspi1_cs2 - gpio_139 - GPS_UART_CTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS2, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     139, "GPS_UART_CTS"),
	/* [IN---] mcspi1_cs3 - gpio_140 - GPS_UART_RTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS3, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     140, "GPS_UART_RTS"),
	/* [-----] uart3_cts_rctx - gpio_141 - GPS_UART_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_CTS_RCTX, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     141, "GPS_UART_TXD"),
	/* [-N-C-] uart3_rts_sd - gpio_142 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_RTS_SD, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     142, "uart3_rts_sd.nc"),
	/* [IN---] uart3_rx_irrx - gpio_143 - AP_FLM_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_RX_IRRX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP
			 | OMAP_PIN_OFF_INPUT_PULLUP,
		     143, "AP_FLM_RXD"),
	/* [IN---] uart3_tx_irtx - gpio_144 - AP_FLM_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_TX_IRTX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     144, "AP_FLM_TXD"),
	/* [-----] sdmmc5_clk - gpio_145 - WLAN_SD_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_CLK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     145, "WLAN_SD_CLK"),
	/* [-----] sdmmc5_cmd - gpio_146 - WLAN_SD_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_CMD, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     146, "WLAN_SD_CMD"),
	/* [-----] sdmmc5_dat0 - gpio_147 - WLAN_SD_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT0, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     147, "WLAN_SD_D(0)"),
	/* [-----] sdmmc5_dat1 - gpio_148 - WLAN_SD_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT1, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     148, "WLAN_SD_D(1)"),
	/* [-----] sdmmc5_dat2 - gpio_149 - WLAN_SD_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT2, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     149, "WLAN_SD_D(2)"),
	/* [-----] sdmmc5_dat3 - gpio_150 - WLAN_SD_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT3, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     150, "WLAN_SD_D(3)"),
	/* [-N-C-] mcspi4_clk - gpio_151 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_CLK, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     151, "mcspi4_clk.nc"),
	/* [-N-C-] mcspi4_simo - gpio_152 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_SIMO, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     152, "mcspi4_simo.nc"),
	/* [--OUT] mcspi4_somi - gpio_153 - TA_nCHG */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_SOMI,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     153, "TA_nCHG"),
	/* [-N-C-] mcspi4_cs0 - gpio_154 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_CS0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     154, "mcspi4_cs0.nc"),
	/* [-----] uart4_rx - gpio_155 - AP_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART4_RX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP
			 | OMAP_PIN_OFF_INPUT_PULLUP,
		     155, "AP_RXD"),
	/* [-----] uart4_tx - gpio_156 - AP_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART4_TX, OMAP_MUX_MODE0 | OMAP_PIN_OFF_OUTPUT_LOW,
		     156, "AP_TXD"),
	/* [IN---] usbb2_ulpitll_clk - gpio_157 - MSENSE_IRQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_CLK,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     157, "MSENSE_IRQ"),
	/* [-N-C-] usbb2_ulpitll_stp - gpio_158 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_STP,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     158, "usbb2_ulpitll_stp.nc"),
	/* [-N-C-] usbb2_ulpitll_dir - gpio_159 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DIR,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     159, "usbb2_ulpitll_dir.nc"),
	/* [-N-C-] usbb2_ulpitll_nxt - gpio_160 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_NXT,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     160, "usbb2_ulpitll_nxt.nc"),
	/* [-N-C-] usbb2_ulpitll_dat0 - gpio_161 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT0,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     161, "usbb2_ulpitll_dat0.nc"),
	/* [-N-C-] usbb2_ulpitll_dat1 - gpio_162 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT1,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     162, "usbb2_ulpitll_dat1.nc"),
	/* [-N-C-] usbb2_ulpitll_dat2 - gpio_163 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT2,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     163, "usbb2_ulpitll_dat2.nc"),
	/* [-N-C-] usbb2_ulpitll_dat3 - gpio_164 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT3,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     164, "usbb2_ulpitll_dat3.nc"),
	/* [-N-C-] usbb2_ulpitll_dat4 - gpio_165 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT4,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     165, "usbb2_ulpitll_dat4.nc"),
	/* [-N-C-] usbb2_ulpitll_dat5 - gpio_166 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT5,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     166, "usbb2_ulpitll_dat5.nc"),
	/* [-N-C-] usbb2_ulpitll_dat6 - gpio_167 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT6,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     167, "usbb2_ulpitll_dat6.nc"),
	/* [-N-C-] usbb2_ulpitll_dat7 - gpio_168 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT7,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     168, "usbb2_ulpitll_dat7.nc"),
	/* [-N-C-] usbb2_hsic_data - gpio_169 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_HSIC_DATA, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     169, "usbb2_hsic_data.nc"),
	/* [-N-C-] usbb2_hsic_strobe - gpio_170 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_HSIC_STROBE,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     170, "usbb2_hsic_strobe.nc"),
	/* [-N-C-] kpd_col3 - gpio_171 - EAR_GND_SEL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     171, "kpd_col3.nc"),
	/* [-N-C-] kpd_col4 - gpio_172 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     172, "kpd_col4.nc"),
	/* [--OUT] kpd_col5 - gpio_173 - GPS_PWR_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL5, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     173, "GPS_PWR_EN"),
	/* [--OUT] kpd_col0 - gpio_174 - VT_CAM_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL0,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     174, "VT_CAM_nRST"),
	/* [-N-C-] kpd_col1 - gpio_0 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     0, "kpd_col1.nc"),
	/* [-N-C-] kpd_col2 - gpio_1 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     1, "kpd_col2.nc"),
	/* [IN---] kpd_row3 - gpio_175 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     175, "kpd_row3.nc"),
	/* [-N-C-] kpd_row4 - gpio_176 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     176, "kpd_row4.nc"),
	/* [-N-C-] kpd_row5 - gpio_177 - SUB_MICBIAS_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     177, "kpd_row5.nc"),
	/* [--OUT] kpd_row0 - gpio_178 - GPS_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW0, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     178, "GPS_nRST"),
	/* [-N-C-] kpd_row1 - gpio_2 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     2, "kpd_row1.nc"),
	/* [-N-C-] kpd_row2 - gpio_3 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     3, "kpd_row2.nc"),
	/* [-N-C-] usba0_otg_ce -  - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_CE, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "usba0_otg_ce.nc"),
	/* [-----] usba0_otg_dp - gpio_179 - AP_D+ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_DP, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     179, "AP_D+"),
	/* [-----] usba0_otg_dm - gpio_180 - AP_D- */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_DM, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     180, "AP_D-"),
	/* [-----] fref_clk0_out - gpio_wk6 - SYS_DRM_MSEC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK0_OUT, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     6, "SYS_DRM_MSEC"),
	/* [-----] fref_clk1_out - gpio_181 - 3M_MCLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     FREF_CLK1_OUT,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     181, "3M_MCLK"),
	/* [-----] fref_clk2_out - gpio_182 - VT_CAM_MCLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     FREF_CLK2_OUT,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     182, "VT_CAM_MCLK"),
	/* [IN---] fref_clk3_req - gpio_wk30 - VOL_UP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK3_REQ,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     30, "VOL_UP"),
	/* [IN---] fref_clk3_out - gpio_wk31 - HOME_KEY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK3_OUT,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     31, "HOME_KEY"),
	/* [-N-C-] fref_clk4_req - gpio_wk7 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK4_REQ, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     7, "fref_clk4_req.nc"),
	/* [IN---] fref_clk4_out - gpio_wk8 - VOL_DN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK4_OUT,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     8, "VOL_DN"),
	/* [IN---] sys_pwron_reset_out - gpio_wk29 - BAT_REMOVAL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_PWRON_RESET_OUT, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     29, "BAT_REMOVAL"),
	/* [-----] sys_nirq1 -  - SYS_nIRQ1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_NIRQ1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     OMAP_MUXTBL_NO_GPIO, "SYS_nIRQ1"),
	/* [-N-C-] sys_nirq2 - gpio_183 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_NIRQ2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     183, "sys_nirq2.nc"),
	/* [-----] sys_boot0 - gpio_184 - SYS_BOOT0 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     184, "SYS_BOOT0"),
	/* [-----] sys_boot1 - gpio_185 - SYS_BOOT1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     185, "SYS_BOOT1"),
	/* [-----] sys_boot2 - gpio_186 - SYS_BOOT2 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     186, "SYS_BOOT2"),
	/* [-----] sys_boot3 - gpio_187 - SYS_BOOT3 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     187, "SYS_BOOT3"),
	/* [-----] sys_boot4 - gpio_188 - SYS_BOOT4 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     188, "SYS_BOOT4"),
	/* [-----] sys_boot5 - gpio_189 - SYS_BOOT5 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     189, "SYS_BOOT5"),
	/* [IN---] sys_boot6 - gpio_wk9 - SYS_BOOT6 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_BOOT6, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     9, "SYS_BOOT6"),
	/* [IN---] sys_boot7 - gpio_wk10 - SYS_BOOT7 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_BOOT7, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     10, "SYS_BOOT7"),
	/* [-----] jtag_ntrst -  - AP_JTAG_nTRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_NTRST, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_nTRST"),
	/* [-----] jtag_tck -  - AP_JTAG_TCK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TCK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TCK"),
	/* [-----] jtag_rtck -  - AP_JTAG_RTCK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_RTCK, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_RTCK"),
	/* [-----] jtag_tms_tmsc -  - AP_JTAG_TMS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TMS_TMSC, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TMS"),
	/* [-----] jtag_tdi -  - AP_JTAG_TDI */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TDI, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TDI"),
	/* [-----] jtag_tdo -  - AP_JTAG_TDO */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TDO, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TDO"),
	/* [-N-C-] dpm_emu0 - gpio_11 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     11, "dpm_emu0.nc"),
	/* [-N-C-] dpm_emu1 - gpio_12 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     12, "dpm_emu1.nc"),
	/* [--OUT] dpm_emu2 - gpio_13 - TA_nCONNECTED */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU2, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     13, "TA_nCONNECTED"),
	/* [-N-C-] dpm_emu3 - gpio_14 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     14, "dpm_emu3.nc"),
	/* [-N-C-] dpm_emu4 - gpio_15 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     15, "dpm_emu4.nc"),
	/* [-N-C-] dpm_emu5 - gpio_16 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     16, "dpm_emu5.nc"),
	/* [-N-C-] dpm_emu6 - gpio_17 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU6, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     17, "dpm_emu6.nc"),
	/* [-N-C-] dpm_emu7 - gpio_18 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU7, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     18, "dpm_emu7.nc"),
	/* [-N-C-] dpm_emu8 - gpio_19 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU8, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     19, "dpm_emu8.nc"),
	/* [-N-C-] dpm_emu9 - gpio_20 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU9, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     20, "dpm_emu9.nc"),
	/* [-N-C-] dpm_emu10 - gpio_21 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU10, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     21, "dpm_emu10.nc"),
	/* [-N-C-] dpm_emu11 - gpio_22 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU11, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     22, "dpm_emu11.nc"),
	/* [-N-C-] dpm_emu12 - gpio_23 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU12, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     23, "dpm_emu12.nc"),
	/* [-N-C-] dpm_emu13 - gpio_24 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU13, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     24, "dpm_emu13.nc"),
	/* [-N-C-] dpm_emu14 - gpio_25 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU14, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     25, "dpm_emu14.nc"),
	/* [-N-C-] dpm_emu15 - gpio_26 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU15, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     26, "dpm_emu15.nc"),
	/* [-N-C-] dpm_emu16 - gpio_27 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU16, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     27, "dpm_emu16.nc"),
	/* [-N-C-] dpm_emu17 - gpio_28 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU17, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     28, "dpm_emu17.nc"),
	/* [-N-C-] dpm_emu18 - gpio_190 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU18, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     190, "dpm_emu18.nc"),
	/* [-N-C-] dpm_emu19 - gpio_191 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU19, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     191, "dpm_emu19.nc"),
};

add_sec_muxtbl_to_list(SEC_MACHINE_GOKEY, 0, muxtbl);
