/* arch/arm/mach-omap2/board-kona-muxset-r04.c
 *
 * Copyright (C) 2012 Samsung Electronics Co, Ltd.
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#include <linux/gpio.h>

#include "board-kona.h"

#include "mux.h"
#include "mux44xx.h"
#include "omap_muxtbl.h"
#include "omap44xx_muxtbl.h"
#include "sec_muxtbl.h"

static struct omap_muxtbl muxtbl[] __initdata = {
	/* [-----] gpmc_ad0.sdmmc2_dat0 - HSMMC_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD0,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(0)"),
	/* [-----] gpmc_ad1.sdmmc2_dat1 - HSMMC_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD1,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(1)"),
	/* [-----] gpmc_ad2.sdmmc2_dat2 - HSMMC_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD2,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(2)"),
	/* [-----] gpmc_ad3.sdmmc2_dat3 - HSMMC_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD3,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(3)"),
	/* [-----] gpmc_ad4.sdmmc2_dat4 - HSMMC_D(4) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD4,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(4)"),
	/* [-----] gpmc_ad5.sdmmc2_dat5 - HSMMC_D(5) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD5,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(5)"),
	/* [-----] gpmc_ad6.sdmmc2_dat6 - HSMMC_D(6) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD6,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(6)"),
	/* [-----] gpmc_ad7.sdmmc2_dat7 - HSMMC_D(7) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD7,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_D(7)"),
	/* [--OUT] gpmc_ad8.gpio_32 - UART_SEL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD8, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     32, "UART_SEL"),
	/* [--OUT] gpmc_ad9.gpio_33 - UART_SEL_FAC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD9, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     33, "UART_SEL_FAC"),
	/* [--OUT] gpmc_ad10.gpio_34 - IRDA_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD10, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     34, "IRDA_WAKE"),
	/* [IN---] gpmc_ad11.gpio_35 - ADC_IC_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD11, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     35, "ADC_IC_INT"),
	/* [--OUT] gpmc_ad12.gpio_36 - EAR_GND_SEL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD12, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     36, "EAR_GND_SEL"),
	/* [--OUT] gpmc_ad13.gpio_37 - AP_DUMP_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD13, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     37, "AP_DUMP_INT"),
	/* [IN---] gpmc_ad14.gpio_38 - ADC_I2C_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD14, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     38, "ADC_I2C_SCL_1.8V"),
	/* [IN---] gpmc_ad15.gpio_39 - ADC_I2C_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_AD15, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     39, "ADC_I2C_SDA_1.8V"),
	/* [--OUT] gpmc_a16.gpio_40 - 5M_nSTBY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A16, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     40, "5M_nSTBY"),
	/* [--OUT] gpmc_a17.gpio_41 - IRDA_IRQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A17, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     41, "IRDA_IRQ"),
	/* [--OUT] gpmc_a18.gpio_42 - PEN_LDO_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A18, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     42, "PEN_LDO_EN"),
	/* [--OUT] gpmc_a19.gpio_43 - MHL_RST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A19, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     43, "MHL_RST"),
	/* [-----] gpmc_a20.safe_mode - NFC_I2C_SCL(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A20, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     44, "NFC_I2C_SCL(nc)"),
	/* [-----] gpmc_a21.safe_mode - NFC_I2C_SDA(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A21, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     45, "NFC_I2C_SDA(nc)"),
	/* [IN---] gpmc_a22.gpio_46 - TOUCH_nINT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A22, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     46, "TOUCH_nINT"),
	/* [IN---] gpmc_a23.gpio_47 - REMOTE_SENSE_IRQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A23, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     47, "REMOTE_SENSE_IRQ"),
	/* [--OUT] gpmc_a24.gpio_48 - MICBIAS_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A24, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     48, "MICBIAS_EN"),
	/* [--OUT] gpmc_a25.gpio_49 - VPS_SOUND_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_A25, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     49, "VPS_SOUND_EN"),
	/* [--OUT] gpmc_ncs0.gpio_50 - RESET_REQ_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS0,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT |
		     OMAP_PIN_OFF_OUTPUT_HIGH,
		     50, "RESET_REQ_N"),
	/* [--OUT] gpmc_ncs1.gpio_51 - USB_PWR_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS1, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     51, "USB_PWR_EN"),
	/* [-N-C-] gpmc_ncs2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     52, "gpmc_ncs2.nc"),
	/* [--OUT] gpmc_ncs3.gpio_53 - CP_ON */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS3,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     53, "CP_ON"),
	/* [-N-C-] gpmc_nwp.gpio_54 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NWP, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     54, "gpmc_nwp.nc"),
	/* [IN---] gpmc_clk.gpio_55 - JIG_ON_18 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_CLK, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     55, "JIG_ON_18"),
	/* [--OUT] gpmc_nadv_ale.gpio_56 - IRDA_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NADV_ALE, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     56, "IRDA_EN"),
	/* [-----] gpmc_noe.sdmmc2_clk - HSMMC_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NOE, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_CLK"),
	/* [-----] gpmc_nwe.sdmmc2_cmd - HSMMC_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NWE,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_OUTPUT_LOW,
		     OMAP_MUXTBL_NO_GPIO, "HSMMC_CMD"),
	/* [-N-C-] gpmc_nbe0_cle.gpio_59 - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NBE0_CLE, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     59, "gpmc_nbe0_cle.nc"),
	/* [--OUT] gpmc_nbe1.gpio_60 - ACCESSORY_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NBE1, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     60, "ACCESSORY_EN"),
	/* [IN---] gpmc_wait0.gpio_61 - FUEL_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT0, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     61, "FUEL_SCL_1.8V"),
	/* [IN---] gpmc_wait1.gpio_62 - FUEL_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT1, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     62, "FUEL_SDA_1.8V"),
	/* [IN---] gpmc_wait2.gpio_100 - TSP_VENDOR1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_WAIT2, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     100, "TSP_VENDOR1"),
	/* [IN---] gpmc_ncs4.gpio_101 - IMA_SLEEP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS4, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     101, "IMA_SLEEP"),
	/* [--OUT] gpmc_ncs5.gpio_102 - IMA_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS5, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     102, "IMA_nRST"),
	/* [--OUT] gpmc_ncs6.gpio_103 - BT_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS6, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     103, "BT_EN"),
	/* [--OUT] gpmc_ncs7.gpio_104 - WLAN_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPMC_NCS7, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     104, "WLAN_EN"),
	/* [IN---] hdmi_hpd.gpio_63 - HDMI_HPD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_HPD, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     63, "HDMI_HPD"),
	/* [-N-C-] hdmi_cec.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_CEC, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     64, "hdmi_cec.nc"),
	/* [-----] hdmi_ddc_scl.hdmi_ddc_scl - MHL_DSCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_DDC_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     65, "MHL_DSCL_1.8V"),
	/* [-----] hdmi_ddc_sda.hdmi_ddc_sda - MHL_DSDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDMI_DDC_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     66, "MHL_DSDA_1.8V"),
	/* [-----] csi21_dx0.csi21_dx0 - 5M_CAM_CLK_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     67, "5M_CAM_CLK_P"),
	/* [-----] csi21_dy0.csi21_dy0 - 5M_CAM_CLK_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     68, "5M_CAM_CLK_N"),
	/* [-----] csi21_dx1.csi21_dx1 - 5M_CAM_D0_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     69, "5M_CAM_D0_P"),
	/* [-----] csi21_dy1.csi21_dy1 - 5M_CAM_D0_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     70, "5M_CAM_D0_N"),
	/* [-----] csi21_dx2.csi21_dx2 - 5M_CAM_D1_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX2,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     71, "5M_CAM_D1_P"),
	/* [-----] csi21_dy2.csi21_dy2 - 5M_CAM_D0_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY2,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     72, "5M_CAM_D0_N"),
	/* [-N-C-] csi21_dx3.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     73, "csi21_dx3.nc"),
	/* [-N-C-] csi21_dy3.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     74, "csi21_dy3.nc"),
	/* [-N-C-] csi21_dx4.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DX4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     75, "csi21_dx4.nc"),
	/* [-N-C-] csi21_dy4.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI21_DY4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     76, "csi21_dy4.nc"),
	/* [-----] csi22_dx0.csi22_dx0 - VT_CAM_CLK_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DX0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     77, "VT_CAM_CLK_P"),
	/* [-----] csi22_dy0.csi22_dy0 - VT_CAM_CLK_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DY0,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     78, "VT_CAM_CLK_N"),
	/* [-----] csi22_dx1.csi22_dx1 - VT_CAM_D0_P */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DX1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     79, "VT_CAM_D0_P"),
	/* [-----] csi22_dy1.csi22_dy1 - VT_CAM_D0_N */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DY1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     80, "VT_CAM_D0_N"),
	/* [-----] cam_shutter.safe_mode - CAM_FLASH_SET(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_SHUTTER, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     81, "CAM_FLASH_SET(nc)"),
	/* [-----] cam_strobe.safe_mode - CAM_FLASH_EN(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_STROBE, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     82, "CAM_FLASH_EN(nc)"),
	/* [--OUT] cam_globalreset.gpio_83 - EAR_BIAS_DISCHARGE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CAM_GLOBALRESET, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     83, "EAR_BIAS_DISCHARGE"),
	/* [-----] usbb1_ulpitll_clk.hsi1_cawake - MIPI_HSI_TX_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_CLK,
		     OMAP_MUX_MODE1 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     84, "MIPI_HSI_TX_WAKE"),
	/* [-----] usbb1_ulpitll_stp.hsi1_cadata - MIPI_HSI_TX_DATA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_STP, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     85, "MIPI_HSI_TX_DATA"),
	/* [-----] usbb1_ulpitll_dir.hsi1_caflag - MIPI_HSI_TX_FLG */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DIR, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     86, "MIPI_HSI_TX_FLG"),
	/* [-----] usbb1_ulpitll_nxt.hsi1_acready - MIPI_HSI_TX_RDY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_NXT,
		     OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     87, "MIPI_HSI_TX_RDY"),
	/* [-----] usbb1_ulpitll_dat0.hsi1_acwake - MIPI_HSI_RX_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT0, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     88, "MIPI_HSI_RX_WAKE"),
	/* [-----] usbb1_ulpitll_dat1.hsi1_acdata - MIPI_HSI_RX_DATA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT1, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     89, "MIPI_HSI_RX_DATA"),
	/* [-----] usbb1_ulpitll_dat2.hsi1_acflag - MIPI_HSI_RX_FLG */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT2, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     90, "MIPI_HSI_RX_FLG"),
	/* [-----] usbb1_ulpitll_dat3.hsi1_caready - MIPI_HSI_RX_RDY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT3, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     91, "MIPI_HSI_RX_RDY"),
	/* [--OUT] usbb1_ulpitll_dat4.gpio_92 - LED_PWM */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT4, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     92, "LED_PWM"),
	/* [-N-C-] usbb1_ulpitll_dat5.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT5,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     93, "usbb1_ulpitll_dat5.nc"),
	/* [IN---] usbb1_ulpitll_dat6.gpio_94 - GPS_CNTL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT6, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     94, "GPS_CNTL"),
	/* [IN---] usbb1_ulpitll_dat7.gpio_95 - CP_DUMP_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_ULPITLL_DAT7, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     95, "CP_DUMP_INT"),
	/* [-N-C-] usbb1_hsic_data.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_HSIC_DATA, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     96, "usbb1_hsic_data.nc"),
	/* [-N-C-] usbb1_hsic_strobe.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB1_HSIC_STROBE,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     97, "usbb1_hsic_strobe.nc"),
	/* [IN---] gpio_wk0.gpio_wk0 - EAR_DET_GND */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     GPIO_WK0,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     0, "EAR_DET_GND"),
	/* [IN---] gpio_wk1.gpio_wk1 - EAR_SEND_END */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     GPIO_WK1,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     1, "EAR_SEND_END"),
	/* [IN---] gpio_wk2.gpio_wk2 - DOCK_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     GPIO_WK2,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     2, "DOCK_INT"),
	/* [IN---] gpio_wk3.gpio_wk3 - EXT_WAKEUP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     GPIO_WK3,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     3, "EXT_WAKEUP"),
	/* [IN---] gpio_wk4.gpio_wk4 - ACCESSORY_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     GPIO_WK4,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     4, "ACCESSORY_INT"),
	/* [IN---] gpio_98.gpio_98 - MHL_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPIO_98, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     98, "MHL_SDA_1.8V"),
	/* [IN---] gpio_99.gpio_99 - MHL_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     GPIO_99, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     99, "MHL_SCL_1.8V"),
	/* [-----] sdmmc1_clk.sdmmc1_clk - TFLASH_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_CLK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     100, "TFLASH_CLK"),
	/* [-----] sdmmc1_cmd.sdmmc1_cmd - TFLASH_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_CMD, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     101, "TFLASH_CMD"),
	/* [-----] sdmmc1_dat0.sdmmc1_dat0 - TFLASH_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT0, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     102, "TFLASH_D(0)"),
	/* [-----] sdmmc1_dat1.sdmmc1_dat1 - TFLASH_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT1, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     103, "TFLASH_D(1)"),
	/* [-----] sdmmc1_dat2.sdmmc1_dat2 - TFLASH_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT2, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     104, "TFLASH_D(2)"),
	/* [-----] sdmmc1_dat3.sdmmc1_dat3 - TFLASH_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT3, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     105, "TFLASH_D(3)"),
	/* [-N-C-] sdmmc1_dat4.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     106, "sdmmc1_dat4.nc"),
	/* [-N-C-] sdmmc1_dat5.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     107, "sdmmc1_dat5.nc"),
	/* [-N-C-] sdmmc1_dat6.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT6, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     108, "sdmmc1_dat6.nc"),
	/* [-N-C-] sdmmc1_dat7.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC1_DAT7, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     109, "sdmmc1_dat7.nc"),
	/* [IN---] abe_mcbsp2_clkx.gpio_110 - CHG_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_CLKX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     110, "CHG_SCL_1.8V"),
	/* [-N-C-] abe_mcbsp2_dr.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_DR, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     111, "abe_mcbsp2_dr.nc"),
	/* [-N-C-] abe_mcbsp2_dx.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_DX, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     112, "abe_mcbsp2_dx.nc"),
	/* [IN---] abe_mcbsp2_fsx.gpio_113 - CHG_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP2_FSX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     113, "CHG_SDA_1.8V"),
	/* [IN---] abe_mcbsp1_clkx.gpio_114 - PEN_SCL_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_CLKX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     114, "PEN_SCL_1.8V"),
	/* [IN---] abe_mcbsp1_dr.gpio_115 - BL_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_DR, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     115, "BL_I2C_SDA"),
	/* [IN---] abe_mcbsp1_dx.gpio_116 - BL_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_DX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     116, "BL_I2C_SCL"),
	/* [IN---] abe_mcbsp1_fsx.gpio_117 - PEN_SDA_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_MCBSP1_FSX, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     117, "PEN_SDA_1.8V"),
	/* [-----] abe_pdm_ul_data.abe_mcbsp3_dr - AP_I2S_DIN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_UL_DATA, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_DIN"),
	/* [-----] abe_pdm_dl_data.abe_mcbsp3_dx - AP_I2S_DOUT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_DL_DATA, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_DOUT"),
	/* [-----] abe_pdm_frame.abe_mcbsp3_clkx - AP_I2S_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_FRAME, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_CLK"),
	/* [-----] abe_pdm_lb_clk.abe_mcbsp3_fsx - AP_I2S_SYNC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_PDM_LB_CLK, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_I2S_SYNC"),
	/* [-N-C-] abe_clks.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_CLKS, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     118, "abe_clks.nc"),
	/* [--OUT] abe_dmic_clk1.gpio_119 - PDA_ACTIVE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_CLK1,
		     OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     119, "PDA_ACTIVE"),
	/* [IN---] abe_dmic_din1.gpio_120 - PHONE_ACTIVE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN1, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     120, "PHONE_ACTIVE"),
	/* [IN---] abe_dmic_din2.gpio_121 - IMA_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN2, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     121, "IMA_I2C_SDA"),
	/* [IN---] abe_dmic_din3.gpio_122 - IMA_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     ABE_DMIC_DIN3, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     122, "IMA_I2C_SCL"),
	/* [-----] uart2_cts.uart2_cts - BT_UART_CTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_CTS, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     123, "BT_UART_CTS"),
	/* [-----] uart2_rts.uart2_rts - BT_UART_RTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_RTS, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     124, "BT_UART_RTS"),
	/* [-----] uart2_rx.uart2_rx - BT_UART_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_RX,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     125, "BT_UART_RXD"),
	/* [-----] uart2_tx.uart2_tx - BT_UART_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART2_TX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     126, "BT_UART_TXD"),
	/* [-N-C-] hdq_sio.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     HDQ_SIO, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     127, "hdq_sio.nc"),
	/* [-----] i2c1_scl.i2c1_scl - PHEONIX_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C1_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PHEONIX_I2C_SCL"),
	/* [-----] i2c1_sda.i2c1_sda - PHEONIX_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C1_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PHEONIX_I2C_SDA"),
	/* [-----] i2c2_scl.i2c2_scl - CAM_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C2_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     128, "CAM_I2C_SCL"),
	/* [-----] i2c2_sda.i2c2_sda - CAM_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C2_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     129, "CAM_I2C_SDA"),
	/* [-----] i2c3_scl.i2c3_scl - TSP_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C3_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     130, "TSP_I2C_SCL"),
	/* [-----] i2c3_sda.i2c3_sda - TSP_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C3_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     131, "TSP_I2C_SDA"),
	/* [-----] i2c4_scl.i2c4_scl - GEN_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C4_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     132, "GEN_I2C_SCL"),
	/* [-----] i2c4_sda.i2c4_sda - GEN_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     I2C4_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     133, "GEN_I2C_SDA"),
	/* [-----] sr_scl.sr_scl - PMIC_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SR_SCL, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PMIC_I2C_SCL"),
	/* [-----] sr_sda.sr_sda - PMIC_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SR_SDA, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "PMIC_I2C_SDA"),
	/* [--OUT] mcspi1_clk.gpio_134 - IMA_CMC_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CLK, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     134, "IMA_CMC_EN"),
	/* [--OUT] mcspi1_somi.gpio_135 - 5M_CAM_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_SOMI, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     135, "5M_CAM_nRST"),
	/* [--OUT] mcspi1_simo.gpio_136 - HDMI_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_SIMO, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     136, "HDMI_EN"),
	/* [--OUT] mcspi1_cs0.gpio_137 - GPS_PWR_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS0, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     137, "GPS_PWR_EN"),
	/* [-----] mcspi1_cs1.uart1_rx - GPS_UART_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS1, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     138, "GPS_UART_RXD"),
	/* [-----] mcspi1_cs2.uart1_cts - GPS_UART_CTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS2, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLDOWN,
		     139, "GPS_UART_CTS"),
	/* [-----] mcspi1_cs3.uart1_rts - GPS_UART_RTS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI1_CS3, OMAP_MUX_MODE1 | OMAP_PIN_INPUT_PULLUP,
		     140, "GPS_UART_RTS"),
	/* [-----] uart3_cts_rctx.uart1_tx - GPS_UART_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_CTS_RCTX, OMAP_MUX_MODE1 | OMAP_PIN_INPUT,
		     141, "GPS_UART_TXD"),
	/* [IN---] uart3_rts_sd.gpio_142 - TA_nCONNECTED */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_RTS_SD,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     142, "TA_nCONNECTED"),
	/* [-----] uart3_rx_irrx.uart3_rx_irrx - AP_UART_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_RX_IRRX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     143, "AP_UART_RXD"),
	/* [-----] uart3_tx_irtx.uart3_tx_irtx - AP_UART_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART3_TX_IRTX, OMAP_MUX_MODE0 | OMAP_PIN_OFF_OUTPUT_LOW,
		     144, "AP_UART_TXD"),
	/* [-----] sdmmc5_clk.sdmmc5_clk - WLAN_SDIO_CLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_CLK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     145, "WLAN_SDIO_CLK"),
	/* [-----] sdmmc5_cmd.sdmmc5_cmd - WLAN_SDIO_CMD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_CMD, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     146, "WLAN_SDIO_CMD"),
	/* [-----] sdmmc5_dat0.sdmmc5_dat0 - WLAN_SDIO_D(0) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT0, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     147, "WLAN_SDIO_D(0)"),
	/* [-----] sdmmc5_dat1.sdmmc5_dat1 - WLAN_SDIO_D(1) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT1, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     148, "WLAN_SDIO_D(1)"),
	/* [-----] sdmmc5_dat2.sdmmc5_dat2 - WLAN_SDIO_D(2) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT2, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     149, "WLAN_SDIO_D(2)"),
	/* [-----] sdmmc5_dat3.sdmmc5_dat3 - WLAN_SDIO_D(3) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SDMMC5_DAT3, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     150, "WLAN_SDIO_D(3)"),
	/* [IN---] mcspi4_clk.gpio_151 - HW_REV0 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_CLK, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     151, "HW_REV0"),
	/* [IN---] mcspi4_simo.gpio_152 - HW_REV2 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_SIMO, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     152, "HW_REV2"),
	/* [IN---] mcspi4_somi.gpio_153 - HW_REV3 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_SOMI, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     153, "HW_REV3"),
	/* [IN---] mcspi4_cs0.gpio_154 - HW_REV1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     MCSPI4_CS0, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     154, "HW_REV1"),
	/* [-----] uart4_rx.uart4_rx - AP_FLM_RXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART4_RX, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     155, "AP_FLM_RXD"),
	/* [-----] uart4_tx.uart4_tx - AP_FLM_TXD */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     UART4_TX, OMAP_MUX_MODE0 | OMAP_PIN_OFF_OUTPUT_LOW,
		     156, "AP_FLM_TXD"),
	/* [-N-C-] usbb2_ulpitll_clk.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_CLK,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     157, "usbb2_ulpitll_clk.nc"),
	/* [-N-C-] usbb2_ulpitll_stp.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_STP,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     158, "usbb2_ulpitll_stp.nc"),
	/* [--OUT] usbb2_ulpitll_dir.gpio_159 - USB_SEL1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DIR, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     159, "USB_SEL1"),
	/* [-N-C-] usbb2_ulpitll_nxt.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_NXT,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     160, "usbb2_ulpitll_nxt.nc"),
	/* [IN---] usbb2_ulpitll_dat0.gpio_161 - IRDA_I2C_SCL */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT0, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     161, "IRDA_I2C_SCL"),
	/* [IN---] usbb2_ulpitll_dat1.gpio_162 - IRDA_I2C_SDA */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT1, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     162, "IRDA_I2C_SDA"),
	/* [IN---] usbb2_ulpitll_dat2.gpio_163 - CODEC_CLK_REQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT2, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     163, "CODEC_CLK_REQ"),
	/* [--OUT] usbb2_ulpitll_dat3.gpio_164 - USB_SEL0 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT3, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     164, "USB_SEL0"),
	/* [-N-C-] usbb2_ulpitll_dat4.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT4,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     165, "usbb2_ulpitll_dat4.nc"),
	/* [-N-C-] usbb2_ulpitll_dat5.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT5,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     166, "usbb2_ulpitll_dat5.nc"),
	/* [-N-C-] usbb2_ulpitll_dat6.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT6,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     167, "usbb2_ulpitll_dat6.nc"),
	/* [-N-C-] usbb2_ulpitll_dat7.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_ULPITLL_DAT7,
		     OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     168, "usbb2_ulpitll_dat7.nc"),
	/* [IN---] usbb2_hsic_data.gpio_169 - HW_REV5 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_HSIC_DATA, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     169, "HW_REV5"),
	/* [IN---] usbb2_hsic_strobe.gpio_170 - HW_REV4 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBB2_HSIC_STROBE, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     170, "HW_REV4"),
	/* [--OUT] kpd_col3.gpio_171 - SUB_MICBIAS_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL3, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     171, "SUB_MICBIAS_EN"),
	/* [-----] kpd_col4.safe_mode - NFC_FIRMWARE(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     172, "NFC_FIRMWARE(nc)"),
	/* [-----] kpd_col5.safe_mode - NFC_EN(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     173, "NFC_EN(nc)"),
	/* [--OUT] kpd_col0.gpio_174 - VT_CAM_nRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL0, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     174, "VT_CAM_nRST"),
	/* [-N-C-] kpd_col1.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     0, "kpd_col1.nc"),
	/* [-N-C-] kpd_col2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_COL2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     1, "kpd_col2.nc"),
	/* [IN---] kpd_row3.gpi_175 - MHL_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW3, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     175, "MHL_INT"),
	/* [-N-C-] kpd_row4.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     176, "kpd_row4.nc"),
	/* [IN---] kpd_row5.gpi_177 - BT_HOST_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW5,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     177, "BT_HOST_WAKE"),
	/* [IN---] kpd_row0.gpi_178 - PEN_PDCT_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW0, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     178, "PEN_PDCT_1.8V"),
	/* [-N-C-] kpd_row1.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     2, "kpd_row1.nc"),
	/* [-N-C-] kpd_row2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     KPD_ROW2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     3, "kpd_row2.nc"),
	/* [-N-C-] usba0_otg_ce.usba0_otg_ce - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_CE, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "usba0_otg_ce.nc"),
	/* [-----] usba0_otg_dp.usba0_otg_dp - AP_DP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_DP, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     179, "AP_DP"),
	/* [-----] usba0_otg_dm.usba0_otg_dm - AP_DM */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     USBA0_OTG_DM, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     180, "AP_DM"),
	/* [--OUT] fref_clk0_out.gpio_wk6 - SYS_DRM_MSEC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK0_OUT, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     6, "SYS_DRM_MSEC"),
	/* [-----] fref_clk1_out.fref_clk1_out - 5M_CAM_MCLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     FREF_CLK1_OUT,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     181, "5M_CAM_MCLK"),
	/* [-----] fref_clk2_out.fref_clk2_out - VT_CAM_MCLK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     FREF_CLK2_OUT,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT | OMAP_PIN_OFF_OUTPUT_LOW,
		     182, "VT_CAM_MCLK"),
	/* [IN---] fref_clk3_req.gpi_wk30 - VOL_UP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK3_REQ,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     30, "VOL_UP"),
	/* [IN---] fref_clk3_out.gpo_wk31 - PS_ALS_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK3_OUT,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     31, "PS_ALS_INT"),
	/* [IN---] fref_clk4_req.gpio_wk7 - PEN_DETECT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK4_REQ,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     7, "PEN_DETECT"),
	/* [IN---] fref_clk4_out.gpio_wk8 - VOL_DOWN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK4_OUT,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     8, "VOL_DOWN"),
	/* [-----] sys_32k.sys_32k - CLK32K_AP */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_32K, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "CLK32K_AP"),
	/* [-----] sys_nrespwron.sys_nrespwron - nRESPWRON */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_NRESPWRON, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "nRESPWRON"),
	/* [-----] sys_nreswarm.sys_nreswarm - nWARM_RESET */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_NRESWARM, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "nWARM_RESET"),
	/* [-----] sys_pwr_req.sys_pwr_req - SYS_PREQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_PWR_REQ, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "SYS_PREQ"),
	/* [IN---] sys_pwron_reset_out.gpio_wk29 - FUEL_ALERT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_PWRON_RESET_OUT,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     29, "FUEL_ALERT"),
	/* [-----] sys_nirq1.sys_nirq1 - SYS_nIRQ1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_NIRQ1,
		     OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     OMAP_MUXTBL_NO_GPIO, "SYS_nIRQ1"),
	/* [-N-C-] sys_nirq2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_NIRQ2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     183, "sys_nirq2.nc"),
	/* [-----] sys_boot0.safe_mode - SYS_BOOT0 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     184, "SYS_BOOT0"),
	/* [-----] sys_boot1.safe_mode - SYS_BOOT1 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     185, "SYS_BOOT1"),
	/* [-----] sys_boot2.safe_mode - SYS_BOOT2 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     186, "SYS_BOOT2"),
	/* [-----] sys_boot3.safe_mode - SYS_BOOT3 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT3, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     187, "SYS_BOOT3"),
	/* [-----] sys_boot4.safe_mode - SYS_BOOT4 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT4, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     188, "SYS_BOOT4"),
	/* [-----] sys_boot5.safe_mode - SYS_BOOT5 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     SYS_BOOT5, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     189, "SYS_BOOT5"),
	/* [IN---] sys_boot6.gpio_wk9 - SYS_BOOT6 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_BOOT6, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     9, "SYS_BOOT6"),
	/* [IN---] sys_boot7.gpio_wk10 - SYS_BOOT7 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     SYS_BOOT7, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLDOWN,
		     10, "SYS_BOOT7"),
	/* [-----] jtag_ntrst.jtag_ntrst - AP_JTAG_nTRST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_NTRST, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_nTRST"),
	/* [-----] jtag_tck.jtag_tck - AP_JTAG_TCK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TCK, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TCK"),
	/* [-----] jtag_rtck.jtag_rtck - AP_JTAG_RTCK */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_RTCK, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_RTCK"),
	/* [-----] jtag_tms_tmsc.jtag_tms_tmsc - AP_JTAG_TMS */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TMS_TMSC, OMAP_MUX_MODE0 | OMAP_PIN_INPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TMS"),
	/* [-----] jtag_tdi.jtag_tdi - AP_JTAG_TDI */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TDI, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLUP,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TDI"),
	/* [-----] jtag_tdo.jtag_tdo - AP_JTAG_TDO */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     JTAG_TDO, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "AP_JTAG_TDO"),
	/* [-N-C-] fref_xtal_in.fref_xtal_in - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_XTAL_IN, OMAP_MUX_MODE0 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "fref_xtal_in.nc"),
	/* [-----] fref_slicer_in.fref_slicer_in - FREF_38.4M_IN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_SLICER_IN, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     5, "FREF_38.4M_IN"),
	/* [-----] fref_clk_ioreq.fref_clk_ioreq - FREF_CLK_REQ */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_WKUP,
		     FREF_CLK_IOREQ, OMAP_MUX_MODE0 | OMAP_PIN_OUTPUT,
		     OMAP_MUXTBL_NO_GPIO, "FREF_CLK_REQ"),
	/* [-N-C-] dpm_emu0.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU0, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     11, "dpm_emu0.nc"),
	/* [-N-C-] dpm_emu1.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU1, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     12, "dpm_emu1.nc"),
	/* [--OUT] dpm_emu2.gpio_13 - LED_BACKLIGHT_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU2, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     13, "LED_BACKLIGHT_EN"),
	/* [--OUT] dpm_emu3.gpio_14 - CODEC_LDO_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU3, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     14, "CODEC_LDO_EN"),
	/* [--OUT] dpm_emu4.gpio_15 - CP_PMU_RST */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU4, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     15, "CP_PMU_RST"),
	/* [IN---] dpm_emu5.gpio_16 - TSP_VENDOR2 */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU5, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     16, "TSP_VENDOR2"),
	/* [-----] dpm_emu6.safe_mode - NFC_IRQ(nc) */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU6, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     17, "NFC_IRQ(nc)"),
	/* [--OUT] dpm_emu7.gpio_18 - LCD_EN */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU7, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     18, "LCD_EN"),
	/* [IN---] dpm_emu8.gpio_19 - ACC_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU8, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     19, "ACC_INT"),
	/* [IN---] dpm_emu9.gpio_20 - IMA_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU9, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     20, "IMA_INT"),
	/* [IN---] dpm_emu10.gpio_21 - PEN_IRQ_1.8V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU10, OMAP_MUX_MODE3 | OMAP_PIN_INPUT_PULLUP,
		     21, "PEN_IRQ_1.8V"),
	/* [-N-C-] dpm_emu11.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU11, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     22, "dpm_emu11.nc"),
	/* [IN---] dpm_emu12.gpio_23 - CHG_INT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU12,
		     OMAP_MUX_MODE3 | OMAP_PIN_INPUT |
		     OMAP_PIN_OFF_WAKEUPENABLE,
		     23, "CHG_INT"),
	/* [IN---] dpm_emu13.gpio_24 - V_ACCESSORY_OUT_5V */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU13, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     24, "V_ACCESSORY_OUT_5V"),
	/* [--OUT] dpm_emu14.gpio_25 - VT_CAM_nSTBY */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU14, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     25, "VT_CAM_nSTBY"),
	/* [IN---] dpm_emu15.gpio_26 - SIM_DETECT */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU15, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     26, "SIM_DETECT"),
	/* [--OUT] dpm_emu16.gpio_27 - BT_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU16, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     27, "BT_WAKE"),
	/* [IN---] dpm_emu17.gpio_28 - WLAN_HOST_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU17, OMAP_MUX_MODE3 | OMAP_PIN_INPUT,
		     28, "WLAN_HOST_WAKE"),
	/* [-----] dpm_emu18.dmtimer10_pwm_evt - MOTOR_PWM */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU18, OMAP_MUX_MODE1 | OMAP_PIN_OUTPUT,
		     190, "MOTOR_PWM"),
	/* [--OUT] dpm_emu19.gpio_191 - WLAN_WAKE */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     DPM_EMU19, OMAP_MUX_MODE3 | OMAP_PIN_OUTPUT,
		     191, "WLAN_WAKE"),
	/* [-N-C-] csi22_dx2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DX2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "csi22_dx2.nc"),
	/* [-N-C-] csi22_dy2.safe_mode - NC */
	OMAP4_MUXTBL(OMAP4_MUXTBL_DOMAIN_CORE,
		     CSI22_DY2, OMAP_MUX_MODE7 | OMAP_PIN_INPUT_PULLDOWN,
		     OMAP_MUXTBL_NO_GPIO, "csi22_dy2.nc"),
};

add_sec_muxtbl_to_list(SEC_MACHINE_KONA, 4, muxtbl);
