# IPC_SPI kernel driver

# obj-$(CONFIG_PHONE_MODEMCTL)		+= modemctl/
obj-$(CONFIG_PHONE_IPC_SPI)	+= ipc_spi/
obj-$(CONFIG_PHONE_SVNET)	+= svnet/
#obj-$(CONFIG_PHONE_IPC_HSI)		+= ipc_hsi/
#obj-$(CONFIG_PHONE_ONEDRAM)		+= onedram/
#obj-$(CONFIG_PHONE_LOOPBACK_TEST)	+= loopback_test/
#obj-$(CONFIG_PHONE_STORAGE)		+= storage/
